[phases.setup]
nixPkgs = ['nodejs', 'gcc']

[phases.install]
cmds = [
  'curl -sS https://bootstrap.pypa.io/get-pip.py | python3',
  'python3 -m pip install -r requirements.txt',
  'npm install -g resume-cli jsonresume-theme-stackoverflow'
]

[start]
cmd = "python3 app.py"
